config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end

  root 'welcome#index'

end

app/models/doc.rb
class Doc < ActiveRecord::Base
  belongs_to :user
  validates :content, length: { minimum: 51 }
  validates :title, length: { maximum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only:[:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
.container
    .row
        .col-lg-12.col-md-12
            = form_for @doc do |f|
                .form-group
                    .col-sm-10
                        = f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Title'
                .form-group
                    .col-sm-10
                        = f.text_area :content, autofocus: true, class: 'form-control form-padding', placeholder: 'Content'
                .form-group
                    .col-sm-10
                        = f.submit 'Add Doc', class: 'btn btn-lg btn-raised btn-primary btn-color btn-padding'

app/views/docs/edit.html.haml
.container
    %h1.text-padding.text-padding-font Fix Doc!

= render 'form'

.container
    = link_to 'Cancel ?', doc_path, class: 'btn btn-lg btn-raised btn-warning btn-color btn-padding'

app/views/docs/index.html.haml
.container.nav-spacing
    .row
        - unless @docs.blank?
            - @docs.each do |doc|
                .col-lg-6.col-md-6
                    .home-card
                        .card
                            %a{ href: (url_for [doc])}
                                .container
                                    %h4= doc.title
                                    %p.content= truncate(doc.content, length:50)
                                    %p.small= time_ago_in_words(doc.created_at)

        - else
            .container
                %h2 Create Doc!
                %p Start Creating Document and Organizing your life!
                %button.btn.btn-lg.btn-raised.btn-primary.btn-color= link_to 'Create Doc', new_doc_path

app/views/docs/new.html.haml
.container
    %h1.text-padding.text-padding-font New Doc!
.row
    = render 'form'

app/views/docs/show.html.haml
.container
    %h1= @doc.title
    %p= @doc.content
    .tags-info
        = link_to 'All Docs', docs_path, class: 'tags'
        = link_to 'Fix Doc', edit_doc_path(@doc), class: 'tags'
        = link_to 'Trash It', doc_path(@doc), method: :delete, data: { confirm: 'Are you sure?'}, class: 'tags'
        

app/views/layouts/application.html.haml
!!!
%html
%head
    %title Evenote | Your life's work
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %body
        %div.navbar.navbar-inverse
            %div.container
                %div.navbar-header
                    %button.navbar-toggle{:data => {:toggle => 'collapse', :target => '.navbar-inverse-collapse'}}
                        %span.icon-bar
                        %span.icon-bar
                        %span.icon-bar
                    = link_to 'Evenote', root_path, class: 'navbar-brand logo'
                %div.navbar-collapse.collapse.navbar-inverse-collapse
                    %ul.nav.navbar-nav.navbar-right
                        - if user_signed_in?
                            %li
                                = link_to 'View Docs', docs_path
                            %li
                                = link_to 'Create Doc', new_doc_path
                            %li
                                = link_to 'Sign Out', destroy_user_session_path, method: :delete
                        - else
                            %li
                                = link_to 'Sign In', new_user_session_path
                            %li
                                = link_to 'Sign Up', new_user_registration_path
                %p= notice
                %p= alert
    = yield

:javascript
    $(document).ready(function() {
        // This command is used to initialize some elements and make them work properly
        $.material.init();
    });

app/views/welcome/index.html.haml
%div.text-center.banner
    %div.banner-inner
        %h1 Evenote
        %p Your life's Work!
        %button.btn.btn-lg.btn-raised.btn-primary.btn-color= link_to "Sign Up", new_user_registration_path
%div.container
    %p= notice
    %p= alert
    #callouts
        .callout_inner
            .wrapper
                .callout
                    .row
                        .col-lg-4
                            = image_tag("icon1.png", height: "210")
                        .col-md-8
                            %h2 Have it everywhere
                            Capture a note once, and it’s instantly available on all your devices. Never worry about where you saved something because it’s in Evernote, and Evenote is wherever you are.

                .callout
                    .row
                        .col-lg-8
                            %h2 Find anything fast
                            Evenote makes sure the notes you’ve saved are easy to find. You can even search for handwritten words buried deep within your notes. 
                        .col-lg-4
                            = image_tag("icon2.png", height: "210")

                .callout
                    .row
                        .col-md-4
                            = image_tag("icon3.png", height: "210")
                        .col-lg-8
                            %h2 Notes
                            Create a project to-do list. Jot down a reminder. Or snap a picture of a sketch. A note can be anything you want it to be. And once you make a note, it’s accessible wherever you go, forever.
                            
%footer.text-center
    %p &copy; #TIA Alex Nayagah